// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Higher")>]
[<assembly: AssemblyProductAttribute("Higher")>]
[<assembly: AssemblyDescriptionAttribute("Lightweight Higher-Kinded Polymorphism")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Higher"
    let [<Literal>] AssemblyProduct = "Higher"
    let [<Literal>] AssemblyDescription = "Lightweight Higher-Kinded Polymorphism"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
